version: '3.3'
services:
  mockminer-10:
    environment:
    - "MINER_MAC=52:54:01:18:92:47"
    restart: always
    logging:
      options:
        max-size: 10m
    image: ghcr.io/northern-data-ag/steiger-fake-whatsminer:0edd849
    networks:
      mining0:
        ipv4_address: 10.5.0.10
  mockminer-11:
    environment:
    - "MINER_MAC=52:54:01:ed:73:cf"
    restart: always
    logging:
      options:
        max-size: 10m
    image: ghcr.io/northern-data-ag/steiger-fake-whatsminer:0edd849
    networks:
      mining0:
        ipv4_address: 10.5.0.11
  mockminer-12:
    environment:
    - "MINER_MAC=52:54:01:54:79:7d"
    restart: always
    logging:
      options:
        max-size: 10m
    image: ghcr.io/northern-data-ag/steiger-fake-whatsminer:0edd849
    networks:
      mining0:
        ipv4_address: 10.5.0.12 

networks:
  mining0:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
