
name: '⚙️ Build Docker image'
on: push
env:
  DOCKER_REGISTRY: ghcr.io
jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Calculate tag names'
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - id: repostring
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ steps.repostring.outputs.lowercase }}:${{ steps.vars.outputs.sha_short }}

